"""empty message

Revision ID: 4504e7858e8e
Revises: 880dfe457eb1
Create Date: 2018-07-16 15:07:56.083343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4504e7858e8e'
down_revision = '880dfe457eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.drop_column('article', 'is_enable')
    op.add_column('category', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.drop_column('category', 'is_enable')
    op.add_column('comment', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.drop_column('comment', 'is_enable')
    op.add_column('users', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_enable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_enable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'enabled')
    op.add_column('comment', sa.Column('is_enable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('comment', 'enabled')
    op.add_column('category', sa.Column('is_enable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('category', 'enabled')
    op.add_column('article', sa.Column('is_enable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('article', 'enabled')
    # ### end Alembic commands ###
