"""empty message

Revision ID: 553736fc1724
Revises: a9f4f67bb099
Create Date: 2018-07-14 00:36:56.675417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '553736fc1724'
down_revision = 'a9f4f67bb099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_name', table_name='tags')
    op.drop_table('article_tag')
    op.drop_table('tags')
    op.add_column('articles', sa.Column('tags', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'tags')
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('utc_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('utc_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_enable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tags_pkey')
    )
    op.create_table('article_tag',
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_tag_article_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='article_tag_tag_id_fkey')
    )
    op.create_index('ix_tags_name', 'tags', ['name'], unique=True)
    # ### end Alembic commands ###
