"""empty message

Revision ID: 8e97205a178a
Revises: f4ef5819c15a
Create Date: 2018-06-20 17:32:08.200672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e97205a178a'
down_revision = 'f4ef5819c15a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_enable', sa.Boolean(), nullable=True))
    op.add_column('tags', sa.Column('is_enable', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.drop_column('tags', 'is_enable')
    op.drop_column('categories', 'is_enable')
    # ### end Alembic commands ###
