"""empty message

Revision ID: 9031cc39a566
Revises: eb1e026f5376
Create Date: 2018-05-14 23:09:17.746604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9031cc39a566'
down_revision = 'eb1e026f5376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_enable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'is_enable')
    # ### end Alembic commands ###
