"""empty message

Revision ID: a9f4f67bb099
Revises: 9b40811f2ce4
Create Date: 2018-07-13 00:02:14.928211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9f4f67bb099'
down_revision = '9b40811f2ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_tag', 'utc_updated')
    op.drop_column('article_tag', 'utc_created')
    op.drop_column('article_tag', 'is_enable')
    op.drop_column('article_tag', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_tag', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('article_tag', sa.Column('is_enable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('article_tag', sa.Column('utc_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('article_tag', sa.Column('utc_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
