"""empty message

Revision ID: de83f3c59756
Revises: 
Create Date: 2019-03-17 17:17:56.418102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de83f3c59756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='最近更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('slug', sa.String(length=16), nullable=False, comment='Slug'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('summary', sa.String(length=200), nullable=True, comment='摘要'),
    sa.Column('content', sa.Text(), nullable=False, comment='正文'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览数'),
    sa.Column('category_id', sa.SmallInteger(), nullable=False, comment='外键，分类的ID'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='外键，用户的ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_author_id'), 'article', ['author_id'], unique=False)
    op.create_index(op.f('ix_article_category_id'), 'article', ['category_id'], unique=False)
    op.create_index(op.f('ix_article_slug'), 'article', ['slug'], unique=True)
    op.create_table('article_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='最近更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='外键，文章的ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='外键，标签的ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'tag_id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='最近更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='名称'),
    sa.Column('is_nav', sa.Boolean(), nullable=True, comment='是否为导航'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='外键，用户的ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'creator_id')
    )
    op.create_index(op.f('ix_category_creator_id'), 'category', ['creator_id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='最近更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('article_id', sa.SmallInteger(), nullable=False, comment='外键，文章的ID'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='昵称'),
    sa.Column('content', sa.String(length=200), nullable=False, comment='内容'),
    sa.Column('website', sa.String(length=256), nullable=True, comment='网站'),
    sa.Column('email', sa.String(length=254), nullable=False, comment='邮箱'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_article_id'), 'comment', ['article_id'], unique=False)
    op.create_table('link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='最近更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('title', sa.String(length=60), nullable=False, comment='标题'),
    sa.Column('href', sa.String(length=256), nullable=False, comment='链接'),
    sa.Column('weight', sa.SmallInteger(), nullable=False, comment='权重'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='外键，用户的ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_creator_id'), 'link', ['creator_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='最近更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='外键，发送消息的用户ID'),
    sa.Column('recipient_id', sa.Integer(), nullable=False, comment='外键，接收消息的用户ID'),
    sa.Column('body', sa.String(length=200), nullable=False, comment='内容'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('side_bar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='最近更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('title', sa.String(length=60), nullable=False, comment='标题'),
    sa.Column('content', sa.String(length=500), nullable=True, comment='内容'),
    sa.Column('display_type', sa.SmallInteger(), nullable=False, comment='展示类型'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='用户的ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_side_bar_creator_id'), 'side_bar', ['creator_id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='最近更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('name', sa.String(length=10), nullable=False, comment='名称'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='用户的ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'creator_id')
    )
    op.create_index(op.f('ix_tag_creator_id'), 'tag', ['creator_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='最近更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('nickname', sa.String(length=32), nullable=False, comment='昵称'),
    sa.Column('email', sa.String(length=64), nullable=False, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='密码'),
    sa.Column('avatar_url', sa.String(length=256), nullable=True, comment='头像URL'),
    sa.Column('bio', sa.String(length=200), nullable=True, comment='个人简历'),
    sa.Column('role', sa.SmallInteger(), nullable=True, comment='用户角色'),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True, comment='读最近一次消息的时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_tag_creator_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_side_bar_creator_id'), table_name='side_bar')
    op.drop_table('side_bar')
    op.drop_table('message')
    op.drop_index(op.f('ix_link_creator_id'), table_name='link')
    op.drop_table('link')
    op.drop_index(op.f('ix_comment_article_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_category_creator_id'), table_name='category')
    op.drop_table('category')
    op.drop_table('article_tag')
    op.drop_index(op.f('ix_article_slug'), table_name='article')
    op.drop_index(op.f('ix_article_category_id'), table_name='article')
    op.drop_index(op.f('ix_article_author_id'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
