"""empty message

Revision ID: f88f9a1e9b3e
Revises: 4d362d31b782
Create Date: 2019-03-19 22:34:08.373101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f88f9a1e9b3e'
down_revision = '4d362d31b782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', column_name='last_login', new_column_name='last_login_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', column_name='last_login_time', new_column_name='last_login')
    # ### end Alembic commands ###
